GET http://localhost:3000

### FIND ALL SONG REQUEST
GET http://localhost:3000/songs?page=1&limit=2

### FIND SONG REQUEST
GET http://localhost:3000/songs/2

### CREATE NEW SONG REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "u and i",
    "artists": [1, 2],
    "releasedDate": "2024-09-30",
    "duration": "02:34",
    "lyrics": "hello from the other world, I hope you are good...."
}

### UPDATE SONG REQUEST
PUT http://localhost:3000/songs/4
Content-Type: application/json

{
    "title": "morayo",
    "artists": ["wizkid", "davido"],
    "releasedDate": "2024-09-29",
    "duration": "02:34",
    "lyrics": "hello from the other world, I hope you are finee...."
}

### DELETE SONG REQUEST
DELETE http://localhost:3000/songs/7


### CREATE USER
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Princewill",
    "lastName": "Duru",
    "email": "princewillD@gmail.com",
    "password": "123456"
}

### LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "princewillD@gmail.com",
    "password": "123456"
}

## ACCESS TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaW5jZXdpbGxEQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzEzMzQxMDkwLCJleHAiOjE3MTM0Mjc0OTB9.AjDpuGjTtohY_oZJG51SExFlej0q-VqGy4v22Ujc0mQ

### PROFILE
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaW5jZXdpbGxEQGdtYWlsLmNvbSIsInN1YiI6MSwiaWF0IjoxNzEzMzQ0MjE3LCJleHAiOjE3MTM0MzA2MTd9.nL20NtXRMT2KyT-E-vgPd8fqxEm-G_xg_JuBueu0B_U