GET http://localhost:3000

### FIND ALL SONG REQUEST
GET http://localhost:3000/songs?page=1&limit=2

### FIND SONG REQUEST
GET http://localhost:3000/songs/2

### CREATE NEW SONG REQUEST
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "woos",
    "artists": ["olamide"],
    "releasedDate": "2024-09-30",
    "duration": "02:34",
    "lyrics": "hello from the other world, I hope you are finee...."
}

### UPDATE SONG REQUEST
PUT http://localhost:3000/songs/4
Content-Type: application/json

{
    "title": "morayo",
    "artists": ["wizkid", "davido"],
    "releasedDate": "2024-09-29",
    "duration": "02:34",
    "lyrics": "hello from the other world, I hope you are finee...."
}

### DELETE SONG REQUEST
DELETE http://localhost:3000/songs/7